version: 1.0.{build}-{branch}-appveyor
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\tools\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
deploy: off
