version: 1.0.{build}.2-{branch}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
environment:
  slack:
    secure: a2FnSHGlcoVzHDV2+FrGWHzIk6e29b01zwFhwmvnHPoYWzN7q9Lz/YaZyQVx5FSPk0QeYaolc2XG/nOr/zMT2sTV022CMsojR0cW2k34OKA=
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\tools\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  auth_token:
    secure: 2sAkDb2JefbXhKjc86n1vzG3GCh/HKsOxuR/66BVIJo+eydS8WCyjxfrPmKsOHzv
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
notifications:
- provider: Slack
  incoming_webhook:
	  secure: {slack}
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
