version: 1.0.{build}.2-appveyor
branches:
  only:
    - master
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
configuration: Release
shallow_clone: true
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\tools\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: 2sAkDb2JefbXhKjc86n1vzG3GCh/HKsOxuR/66BVIJo+eydS8WCyjxfrPmKsOHzv
  artifact: .\artifacts\*.nupkg
  force_update: true
