version: 1.0.{build}.2
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
shallow_clone: true
environment:
  slack:
    secure: a2FnSHGlcoVzHDV2+FrGWHzIk6e29b01zwFhwmvnHPoYWzN7q9Lz/YaZyQVx5FSPlYRD+17oN/h/EhLgBbxcPnzda+dTDHk5oeEcGYK1gH0=
  gitter:
    secure: UV7Fp0WMRE8es4ZJYaT8U2CWvIjvzwom3pB+cJxbJTlwVT1kLwXvsjZzLVnCsJuJD4cI0DAJDxrCjtNlSNX66g==
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\tools\Build.ps1
test: off
artifacts:
- path: .\artifacts\*.nupkg
deploy:
- provider: GitHub
  tag: $(appveyor_build_version)
  auth_token:
    secure: 2sAkDb2JefbXhKjc86n1vzG3GCh/HKsOxuR/66BVIJo+eydS8WCyjxfrPmKsOHzv
  artifact: /.*\.nupkg/
  force_update: true
  on:
    branch: master
- provider: NuGet
  api_key:
    secure: N5CugTZvJpt3kz6I7grx6yaBOj17WxSM5Jx6VtcYe3giunupExW+QoUXvpkwV3fQ
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: /^(master|dev)$/
notifications:
- provider: Slack
  incoming_webhook:
    secure: a2FnSHGlcoVzHDV2+FrGWHzIk6e29b01zwFhwmvnHPoYWzN7q9Lz/YaZyQVx5FSPlYRD+17oN/h/EhLgBbxcPnzda+dTDHk5oeEcGYK1gH0=
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
- provider: Webhook
  url:
    secure: UV7Fp0WMRE8es4ZJYaT8U2CWvIjvzwom3pB+cJxbJTlwVT1kLwXvsjZzLVnCsJuJD4cI0DAJDxrCjtNlSNX66g==
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
