@host = localhost:47920

### @name V1ApiValues

GET /api/v1/values HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthCheck

GET /api/healthcheck HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name LivenessCheck
GET /liveness HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name Health

GET /health HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthReady

GET /health/ready HTTP/1.1
Host: {{host}}
Cache-Control: no-cache


### @name HealthLive

GET /health/live HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthCustom

GET /health/custom HTTP/1.1
Host: {{host}}
Cache-Control: no-cache


### @name HealthBeatpulse

GET /health/beatpulse HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthBeatpulseApi

GET /health/beatpulse-api HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthBeatpulseWebhooks

GET /health/beatpulse-webhooks HTTP/1.1
Host: {{host}}
Cache-Control: no-cache

### @name HealthBeatpulseUi

GET /health/beatpulse-ui HTTP/1.1
Host: {{host}}
Cache-Control: no-cache
