nuget pack burcin.nuspec;
dotnet new -i Burcin.ConsoleTemplate.CSharp.0.0.1.nupkg;
Remove-Item .\Burcin.ConsoleTemplate.CSharp.0.0.1.nupkg;
Remove-Item -Recurse -Force "Bedia";
New-Item -ItemType "directory" -Name "Bedia";
Set-Location "Bedia";
dotnet new burcinconsole --ConsoleApplication --BackgroundService --HealthChecks --EntityFramework --TestFramework --DockerSupport --Swagger --VsCodeDirectory --GithubTemplates --Cache "Both" --DatabaseName "BediaDb" --Authors "Cengiz Ilerler" --RepositoryUrl "https://github.com/cilerler/bedia" --SkipRestore;
dotnet new -u Burcin.ConsoleTemplate.CSharp.0.0.1;
code .;
cd ..;
